name: Build Tag to Container

on: 
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go 1.25.6
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.6'
      - name: Test
        run: go test -v ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up emulation
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: |
            ghcr.io/leemartin77/handicap:latest
            ghcr.io/leemartin77/handicap:${{ github.ref_name }}
          context: .
          platforms: linux/arm64/v8,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max