// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Administrator struct {
	ID pgtype.UUID
}

type Club struct {
	ID   pgtype.UUID
	Name string
	Slug string
}

type ClubOrganiser struct {
	ClubID   pgtype.UUID
	RunnerID pgtype.UUID
}

type ClubRunner struct {
	ClubID   pgtype.UUID
	RunnerID pgtype.UUID
}

type Event struct {
	ClubID pgtype.UUID
	ID     pgtype.UUID
	Name   string
	Slug   string
	Date   pgtype.Date
	Time   pgtype.Time
}

type EventFinisher struct {
	ID             pgtype.UUID
	EventID        pgtype.UUID
	Position       int64
	TimeSeconds    int64
	EventStarterID pgtype.UUID
}

type EventStarter struct {
	ID                   pgtype.UUID
	EventID              pgtype.UUID
	ProjectedTimeSeconds int64
	RunnerID             pgtype.UUID
	PlaceholderName      pgtype.Text
}

type Login struct {
	ID         pgtype.UUID
	Provider   string
	Identifier string
}

type Runner struct {
	ID         pgtype.UUID
	GivenName  pgtype.Text
	FamilyName pgtype.Text
}

type RunnerLogin struct {
	LoginID  pgtype.UUID
	RunnerID pgtype.UUID
}

type RunnerTime struct {
	RunnerID    pgtype.UUID
	ID          pgtype.UUID
	Date        pgtype.Date
	Time        pgtype.Time
	TimeSeconds int64
	Name        string
	Description pgtype.Text
}

type TestDatum struct {
	TestValue pgtype.Text
}
