// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runner.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRunner = `-- name: GetRunner :one
SELECT id, given_name, family_name
FROM runner
WHERE id = $1
`

func (q *Queries) GetRunner(ctx context.Context, id pgtype.UUID) (Runner, error) {
	row := q.db.QueryRow(ctx, getRunner, id)
	var i Runner
	err := row.Scan(&i.ID, &i.GivenName, &i.FamilyName)
	return i, err
}
